[features]
seeds = false
skip-lint = false

[programs.localnet]
otc_trades = "26PFg6NB6bLYFXJYHdVUxzdYGqa3ceoURsGCDtEo9wtm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"

[toolchain]
anchor_version = "0.29.0"