pub const MAX_TRANSACTION_TITLE_LENGTH: usize = 200;
pub const MAX_TRANSACTION_CONTENT_LENGTH: usize = 200;
pub const MAX_TRANSACTION_LIST_LENGTH: usize = 8;

pub const MAX_TOKEN_HOLDING_LIST_LENGTH: usize = 8;

pub const USER_ACCOUNT_DATA_SEED: &[u8] = 256;
pub const USER_ACCOUNT_DATA_MAX_SIZE: usize = 2048;